Trial Project To Be Admitted In To Microverse
citec-47/code-reviewing pull request #1
Opened 2023-01-16 10:19 UTC by citec-47

Tribute Page🧾
-Footballl

2023-01-16 11:47 UTC, ndonyi12345 reviewed
#Hi CITEC-47
-You have done an excellent job 
*No linter errors
*Nice styling
#Here are the changes required
-README 
-SETUP
<img src="https://media.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy.gif>

2023-01-16 11:47 UTC, ndonyi12345 commented on style.css
> +
#please remove all the spaces it does not make your work professional

2023-01-16 11:47 UTC, ndonyi12345 commented on style.css
> +
#please they are lots of spaces in your code

2023-01-16 11:47 UTC, ndonyi12345 commented on style.css
> +
<a href="https://media.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

2023-01-16 11:47 UTC, ndonyi12345 commented on style.css
> +
#Hi CITEC-47
-You have done an excellent job 
*No linter errors
*Nice styling
#Here are the changes required
-README 
-SETUP
<img src="https://media.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy.gif>

2023-01-16 12:41 UTC, didierganthier requested changes
Hi @citec-47 ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/cLwDB2j2a7JFdzQzYu/giphy.gif" />

## Highlights
- Inline comments ✔️ 

## Required Changes 🛠
- [ ] The review in the Pull Request should be opened utilizing the "Review changes" feature from GitHub.
- [ ] Try to phrase the comments politely, as suggestions instead of orders. For example:
    * This is a polite suggestion: *"I think it would be better to use semantic tags"*
    * This reads as an order: *"Use semantic tags"*
- [ ] Make sure it includes an explanation, a "why", for each requested change. For example:
    * This is a well-explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
    * This request lacks a "why": *Why don't you use an article tag here instead of a div?*

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-01-17 11:31 UTC, citec-47 reviewed
#Hi CITEC-47
-You have done an excellent job ✔
*No linter errors✔
*Nice styling😍👌
<img src="https://media.giphy.com/media/FpKKILCKqNIgIE1GZf/giphy.gif">
#Here are the changes required
-Please set up your README📑 page professionally.
-SETUP Please tell us how we can run this application by providing the set up
#You have done a great job ✔

2023-01-17 11:31 UTC, citec-47 commented on index.html
> +
You did a great job implementing this project, but I suggest you remove these empty spaces to make it looks good. 😁

2023-01-17 11:31 UTC, citec-47 commented on style.css
> +
I also suggest you remove the empty spaces here to make it look cool.

2023-01-17 11:55 UTC, TuyishimireEric commented on style.css
> +
- [ ] **Good review so far :clap:** however, As suggested by the previous reviewer, I think it would be better to include a clear explanation, a **"why"**, for each requested change. to help the reader to understand your perspective and the reasoning behind your opinion. It will also make the review more informative and helpful 😎😎

2023-01-17 11:57 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @citec-47   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far 👍 
 there are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔ Professional PR

## Required Changes ♻️
_Check the comment under your review ☝️_

## Optional request 
- [ ] **[Optional]** I think It would be better to use a couple of emojis or gifs in the review to make the code review more human-friendly 👽😍

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 02:56 UTC, Shedrack-Sunday approved these changes
Hi @citec-47   👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
- Proper use of Github features 💯 
- Good commit messages 
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 

 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 03:02 UTC, merged